arcgis_api:
  urls:
    - https://services.arcgis.com/JJzESW51TqeY9uat/arcgis/rest/services/CRoW_Act_2000_Access_Layer/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson
    - https://services-eu1.arcgis.com/NPIbx47lsIiu2pqz/arcgis/rest/services/National_Trust_Open_Data_Land_Always_Open/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson
    - https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LAU1_Dec_2015_GCB_in_England_and_Wales_2022/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson
  names:
    - defra_crow_oa
    - national_trust_oa
    - local_authority_boundaries
ons_postcodes:
  url: https://www.arcgis.com/sharing/rest/content/items/a2f8c9c5778a452bbf640d98c166657c/data
